<?php

/**
 *
 * @link              velocitydeveloper.com
 * @since             1.2.0
 * @package           whatsapp-ads
 *
 **/

 function create_new_page()
{
    global $user_ID;
    if( get_page_by_title('Form Chat') == NULL ) {
	$new_post = array(
		      'post_title' => 'Form Chat',
		      'post_content' => '[chat-form]',
		      'post_status' => 'publish',
		      'post_date' => date('Y-m-d H:i:s'),
		      'post_author' => $user_ID,
		      'post_type' => 'page'
		);
	$post_id = wp_insert_post($new_post);
   }
}
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

 class WhatsappAds {
	private $whatsapp_ads_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'whatsapp_ads_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'whatsapp_ads_page_init' ) );
	}

	public function whatsapp_ads_add_plugin_page() {
		add_menu_page(
			'Whatsapp Ads', // page_title
			'Whatsapp Ads', // menu_title
			'manage_options', // capability
			'whatsapp-ads', // menu_slug
			array( $this, 'whatsapp_ads_create_admin_page' ), // function
			'dashicons-admin-generic', // icon_url
			2 // position
		);
	}

	public function whatsapp_ads_create_admin_page() {
		$this->whatsapp_ads_options = get_option( 'whatsapp_ads' ); ?>

		<div class="wrap">
			<h2>Whatsapp Ads</h2>
			<p>Velocity Whatsapp Setting</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'whatsapp_ads_option_group' );
					do_settings_sections( 'whatsapp-ads-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function whatsapp_ads_page_init() {
		register_setting(
			'whatsapp_ads_option_group', // option_group
			'whatsapp_ads', // option_name
			array( $this, 'whatsapp_ads_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'whatsapp_ads_setting_section', // id
			'Settings', // title
			array( $this, 'whatsapp_ads_section_info' ), // callback
			'whatsapp-ads-admin' // page
		);

		add_settings_field(
			'no_whatsapp_0', // id
			'No. Whatsapp', // title
			array( $this, 'no_whatsapp_0_callback' ), // callback
			'whatsapp-ads-admin', // page
			'whatsapp_ads_setting_section' // section
		);

		add_settings_field(
			'tampilkan_whatsapp_melayang_1', // id
			'Tampilkan Whatsapp melayang', // title
			array( $this, 'tampilkan_whatsapp_melayang_1_callback' ), // callback
			'whatsapp-ads-admin', // page
			'whatsapp_ads_setting_section' // section
		);

		add_settings_field(
			'arahkan_ke_form_chat_2', // id
			'Arahkan Ke form Chat', // title
			array( $this, 'arahkan_ke_form_chat_2_callback' ), // callback
			'whatsapp-ads-admin', // page
			'whatsapp_ads_setting_section' // section
		);
	}

	public function whatsapp_ads_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['no_whatsapp_0'] ) ) {
			$sanitary_values['no_whatsapp_0'] = sanitize_text_field( $input['no_whatsapp_0'] );
		}

		if ( isset( $input['tampilkan_whatsapp_melayang_1'] ) ) {
			$sanitary_values['tampilkan_whatsapp_melayang_1'] = $input['tampilkan_whatsapp_melayang_1'];
		}

		if ( isset( $input['arahkan_ke_form_chat_2'] ) ) {
			$sanitary_values['arahkan_ke_form_chat_2'] = $input['arahkan_ke_form_chat_2'];
		}

		return $sanitary_values;
	}

	public function whatsapp_ads_section_info() {
		
	}

	public function no_whatsapp_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="whatsapp_ads[no_whatsapp_0]" id="no_whatsapp_0" value="%s">',
			isset( $this->whatsapp_ads_options['no_whatsapp_0'] ) ? esc_attr( $this->whatsapp_ads_options['no_whatsapp_0']) : ''
		);
	}

	public function tampilkan_whatsapp_melayang_1_callback() {
		printf(
			'<input type="checkbox" name="whatsapp_ads[tampilkan_whatsapp_melayang_1]" id="tampilkan_whatsapp_melayang_1" value="tampilkan_whatsapp_melayang_1" %s> <label for="tampilkan_whatsapp_melayang_1">Juka di centang akan menampilkan tombol whatsapp melayang di pojok kanan.</label>',
			( isset( $this->whatsapp_ads_options['tampilkan_whatsapp_melayang_1'] ) && $this->whatsapp_ads_options['tampilkan_whatsapp_melayang_1'] === 'tampilkan_whatsapp_melayang_1' ) ? 'checked' : ''
		);
	}

	public function arahkan_ke_form_chat_2_callback() {
		printf(
			'<input type="checkbox" name="whatsapp_ads[arahkan_ke_form_chat_2]" id="arahkan_ke_form_chat_2" value="arahkan_ke_form_chat_2" %s> <label for="arahkan_ke_form_chat_2">Jika di centang semua link whatsapp perlu validasi dengan mengisi data form.</label>',
			( isset( $this->whatsapp_ads_options['arahkan_ke_form_chat_2'] ) && $this->whatsapp_ads_options['arahkan_ke_form_chat_2'] === 'arahkan_ke_form_chat_2' ) ? 'checked' : ''
		);
	}

}
if ( is_admin() )
	$whatsapp_ads = new WhatsappAds();

/* 
 * Retrieve this value with:
 * $whatsapp_ads_options = get_option( 'whatsapp_ads' ); // Array of All Options
 * $no_whatsapp_0 = $whatsapp_ads_options['no_whatsapp_0']; // No. Whatsapp
 * $tampilkan_whatsapp_melayang_1 = $whatsapp_ads_options['tampilkan_whatsapp_melayang_1']; // Tampilkan Whatsapp melayang
 * $arahkan_ke_form_chat_2 = $whatsapp_ads_options['arahkan_ke_form_chat_2']; // Arahkan Ke form Chat
 */
