<?php

/**
 *
 * @link              velocitydeveloper.com
 * @since             1.2.0
 * @package           whatsapp-ads
 *
 **/

 function create_new_page() {
    global $user_ID;

    if (get_page_by_title('Form Chat') == NULL) {
        $new_post = array(
            'post_title' => 'Form Chat',
            'post_content' => '[chat-form]',
            'post_status' => 'publish',
            'post_date' => date('Y-m-d H:i:s'),
            'post_author' => $user_ID,
            'post_type' => 'page'
        );

        $post_id = wp_insert_post($new_post);
    }
}

create_new_page();
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

 class WhatsappAds {
	private $whatsapp_ads_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'whatsapp_ads_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'whatsapp_ads_page_init' ) );
	}

	public function whatsapp_ads_add_plugin_page() {
		add_menu_page(
			'Whatsapp Ads', // page_title
			'Whatsapp Ads', // menu_title
			'manage_options', // capability
			'whatsapp-ads', // menu_slug
			array( $this, 'whatsapp_ads_create_admin_page' ), // function
			'dashicons-admin-generic', // icon_url
			2 // position
		);
	}

	public function whatsapp_ads_create_admin_page() {
		$this->whatsapp_ads_options = get_option( 'whatsapp_ads' ); ?>

		<div class="wrap">
			<h2>Whatsapp Ads</h2>
			<p>Velocity Whatsapp Setting. Untuk menampilkan link whatsapp dengan kondisi dibawah bisa menggunakan shortcode [link-whatsapp]</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'whatsapp_ads_option_group' );
					do_settings_sections( 'whatsapp-ads-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function whatsapp_ads_page_init() {
		register_setting(
			'whatsapp_ads_option_group', // option_group
			'whatsapp_ads', // option_name
			array( $this, 'whatsapp_ads_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'whatsapp_ads_setting_section', // id
			'Settings', // title
			array( $this, 'whatsapp_ads_section_info' ), // callback
			'whatsapp-ads-admin' // page
		);

		add_settings_field(
			'no_whatsapp_0', // id
			'No. Whatsapp', // title
			array( $this, 'no_whatsapp_0_callback' ), // callback
			'whatsapp-ads-admin', // page
			'whatsapp_ads_setting_section' // section
		);

		add_settings_field(
			'pesan_whatsapp', // id
			'Pesan Whatsapp', // title
			array( $this, 'pesan_whatsapp_callback' ), // callback
			'whatsapp-ads-admin', // page
			'whatsapp_ads_setting_section' // section
		);

		add_settings_field(
			'tampilkan_whatsapp_melayang_1', // id
			'Tampilkan Whatsapp melayang', // title
			array( $this, 'tampilkan_whatsapp_melayang_1_callback' ), // callback
			'whatsapp-ads-admin', // page
			'whatsapp_ads_setting_section' // section
		);

		add_settings_field(
			'arahkan_ke_form_chat_2', // id
			'Arahkan Ke form Chat', // title
			array( $this, 'arahkan_ke_form_chat_2_callback' ), // callback
			'whatsapp-ads-admin', // page
			'whatsapp_ads_setting_section' // section
		);
	}

	public function whatsapp_ads_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['no_whatsapp_0'] ) ) {
			$sanitary_values['no_whatsapp_0'] = sanitize_text_field( $input['no_whatsapp_0'] );
		}

		if ( isset( $input['pesan_whatsapp'] ) ) {
			$sanitary_values['pesan_whatsapp'] = sanitize_text_field( $input['pesan_whatsapp'] );
		}

		if ( isset( $input['tampilkan_whatsapp_melayang_1'] ) ) {
			$sanitary_values['tampilkan_whatsapp_melayang_1'] = $input['tampilkan_whatsapp_melayang_1'];
		}

		if ( isset( $input['arahkan_ke_form_chat_2'] ) ) {
			$sanitary_values['arahkan_ke_form_chat_2'] = $input['arahkan_ke_form_chat_2'];
		}

		return $sanitary_values;
	}

	public function whatsapp_ads_section_info() {
		
	}

	public function no_whatsapp_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="whatsapp_ads[no_whatsapp_0]" id="no_whatsapp_0" value="%s">',
			isset( $this->whatsapp_ads_options['no_whatsapp_0'] ) ? esc_attr( $this->whatsapp_ads_options['no_whatsapp_0']) : ''
		);
	}

	public function pesan_whatsapp_callback() {
		printf(
			'<input class="regular-text" type="text" name="whatsapp_ads[pesan_whatsapp]" id="pesan_whatsapp" value="%s">',
			isset( $this->whatsapp_ads_options['pesan_whatsapp'] ) ? esc_attr( $this->whatsapp_ads_options['pesan_whatsapp']) : ''
		);
	}

	public function tampilkan_whatsapp_melayang_1_callback() {
		printf(
			'<input type="checkbox" name="whatsapp_ads[tampilkan_whatsapp_melayang_1]" id="tampilkan_whatsapp_melayang_1" value="tampilkan_whatsapp_melayang_1" %s> <label for="tampilkan_whatsapp_melayang_1">Juka di centang akan menampilkan tombol whatsapp melayang di pojok kanan.</label>',
			( isset( $this->whatsapp_ads_options['tampilkan_whatsapp_melayang_1'] ) && $this->whatsapp_ads_options['tampilkan_whatsapp_melayang_1'] === 'tampilkan_whatsapp_melayang_1' ) ? 'checked' : ''
		);
	}

	public function arahkan_ke_form_chat_2_callback() {
		printf(
			'<input type="checkbox" name="whatsapp_ads[arahkan_ke_form_chat_2]" id="arahkan_ke_form_chat_2" value="arahkan_ke_form_chat_2" %s> <label for="arahkan_ke_form_chat_2">Jika di centang semua link whatsapp perlu validasi dengan mengisi data form.</label>',
			( isset( $this->whatsapp_ads_options['arahkan_ke_form_chat_2'] ) && $this->whatsapp_ads_options['arahkan_ke_form_chat_2'] === 'arahkan_ke_form_chat_2' ) ? 'checked' : ''
		);
	}

}
if ( is_admin() )
	$whatsapp_ads = new WhatsappAds();

/* 
 * Retrieve this value with:
 * $whatsapp_ads_options = get_option( 'whatsapp_ads' ); // Array of All Options
 * $no_whatsapp_0 = $whatsapp_ads_options['no_whatsapp_0']; // No. Whatsapp
 * $tampilkan_whatsapp_melayang_1 = $whatsapp_ads_options['tampilkan_whatsapp_melayang_1']; // Tampilkan Whatsapp melayang
 * $arahkan_ke_form_chat_2 = $whatsapp_ads_options['arahkan_ke_form_chat_2']; // Arahkan Ke form Chat
 */


 add_action( 'wp_footer', 'wp_footer_whatsapp' );
if(! function_exists('wp_footer_whatsapp')){
    /**
     * wp footer whatsapp floating
     */
    function wp_footer_whatsapp() {
		$whatsapp_ads_options = get_option( 'whatsapp_ads' );
		$tampilkan_whatsapp_melayang_1 = isset($whatsapp_ads_options['tampilkan_whatsapp_melayang_1']) ? $whatsapp_ads_options['tampilkan_whatsapp_melayang_1'] : ''; // Tampilkan Whatsapp melayang
		$pesan_whatsapp = isset($whatsapp_ads_options['pesan_whatsapp']) ? $whatsapp_ads_options['pesan_whatsapp'] : 'Butuh bantuan?'; // Tampilkan Whatsapp melayang
		$no_whatsapp = isset($whatsapp_ads_options['no_whatsapp_0']) ? $whatsapp_ads_options['no_whatsapp_0'] : '';
		$arahkan_ke_form_chat = isset($whatsapp_ads_options['arahkan_ke_form_chat_2']) ? $whatsapp_ads_options['arahkan_ke_form_chat_2'] : ''; // Arahkan Ke form Chat
		// Hilangkan semua karakter kecuali angka
		$no_whatsapp = preg_replace('/[^0-9]/', '', $no_whatsapp);

		// Ganti "0" di awal nomor dengan "62"
		if (substr($no_whatsapp, 0, 1) == '0') {
			$no_whatsapp = '62' . substr($no_whatsapp, 1);
		}
		if($arahkan_ke_form_chat) {
			$no_whatsapp = get_site_url().'/form-chat';
			$target = '';
		} else {
			$no_whatsapp = 'https://wa.me/'.$no_whatsapp;
			$target = '_blank';
		}
        if($tampilkan_whatsapp_melayang_1 && wp_is_mobile()) {
            ?>
            <div class="whatsapp-ads-floating whatsapp-floating floating-button right scroll-active scroll-right pull-left">
                <a href="<?php echo $no_whatsapp; ?>" target="<?php echo $target; ?>" style="color:#fff;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-whatsapp" viewBox="0 0 16 16">
                        <path d="M13.601 2.326A7.854 7.854 0 0 0 7.994 0C3.627 0 .068 3.558.064 7.926c0 1.399.366 2.76 1.057 3.965L0 16l4.204-1.102a7.933 7.933 0 0 0 3.79.965h.004c4.368 0 7.926-3.558 7.93-7.93A7.898 7.898 0 0 0 13.6 2.326zM7.994 14.521a6.573 6.573 0 0 1-3.356-.92l-.24-.144-2.494.654.666-2.433-.156-.251a6.56 6.56 0 0 1-1.007-3.505c0-3.626 2.957-6.584 6.591-6.584a6.56 6.56 0 0 1 4.66 1.931 6.557 6.557 0 0 1 1.928 4.66c-.004 3.639-2.961 6.592-6.592 6.592zm3.615-4.934c-.197-.099-1.17-.578-1.353-.646-.182-.065-.315-.099-.445.099-.133.197-.513.646-.627.775-.114.133-.232.148-.43.05-.197-.1-.836-.308-1.592-.985-.59-.525-.985-1.175-1.103-1.372-.114-.198-.011-.304.088-.403.087-.088.197-.232.296-.346.1-.114.133-.198.198-.33.065-.134.034-.248-.015-.347-.05-.099-.445-1.076-.612-1.47-.16-.389-.323-.335-.445-.34-.114-.007-.247-.007-.38-.007a.729.729 0 0 0-.529.247c-.182.198-.691.677-.691 1.654 0 .977.71 1.916.81 2.049.098.133 1.394 2.132 3.383 2.992.47.205.84.326 1.129.418.475.152.904.129 1.246.08.38-.058 1.171-.48 1.338-.943.164-.464.164-.86.114-.943-.049-.084-.182-.133-.38-.232z"/>
                    </svg>
                    <span><?php echo $pesan_whatsapp; ?></span>
                </a>
            </div>
            <?php
        }
    }
}

// Fungsi untuk menambahkan custom page template
function custom_page_templates_plugin() {
    $plugin_path = plugin_dir_path(__FILE__);
    $template_dir = $plugin_path . 'templates/';

    $templates = array(
        'page-blank.php' => 'Page Blank Template',
    );

    foreach ($templates as $template_file => $template_name) {
        add_filter('theme_page_templates', function ($templates) use ($template_file, $template_name) {
            $templates[$template_file] = $template_name;
            return $templates;
        });
        add_filter('page_template_hierarchy', function ($templates) use ($template_dir, $template_file) {
            array_unshift($templates, $template_dir . $template_file);
            return $templates;
        });
    }
}

add_action('plugins_loaded', 'custom_page_templates_plugin');